services:
  # Banco de Dados
  db:
    image: postgres:15
    container_name: SDDB2_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: l1l2r1r2
      POSTGRES_DB: dados_inep
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: